# Generated by Django 5.1.7 on 2025-03-07 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="created_at",
            new_name="create_dtm",
        ),
    ]
