# Generated by Django 5.1.7 on 2025-03-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("email", models.TextField()),
                ("phone", models.BigIntegerField()),
                ("phone_ext", models.SmallIntegerField()),
                ("links", models.JSONField()),
            ],
        ),
    ]
