# Generated by Django 5.1.7 on 2025-03-14 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("helpercat", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
