# Generated by Django 5.1.7 on 2025-03-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("helpercat", "0002_rename_users_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserInfo",
        ),
    ]
