# Generated by Django 5.1.7 on 2025-03-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpercat", "0003_rename_user_userinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worker_id", models.IntegerField()),
                ("establishment", models.TextField()),
                ("degree_cert", models.TextField()),
                ("major", models.TextField()),
                ("minor", models.TextField()),
                ("concentration", models.TextField()),
                ("city", models.TextField()),
                ("gpa", models.FloatField()),
                ("extracirriculars", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proj_id", models.IntegerField()),
                ("experience", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProjectsMetadata",
            fields=[
                ("proj_id", models.IntegerField(primary_key=True, serialize=False)),
                ("worker_id", models.IntegerField()),
                ("title", models.TextField()),
                ("link", models.TextField()),
                ("org", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worker_id", models.IntegerField()),
                ("skill", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exp_id", models.IntegerField()),
                ("experience", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperienceMetadata",
            fields=[
                ("exp_id", models.IntegerField(primary_key=True, serialize=False)),
                ("worker_id", models.IntegerField()),
                ("company", models.TextField()),
                ("title", models.TextField()),
                ("location", models.TextField()),
                ("onsite_sts", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name="userinfo",
            old_name="id",
            new_name="worker_id",
        ),
    ]
